// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADOyw9frgMixaJJ2KBGS6YQ7pmSmEMc6o',
    appId: '1:826385888674:web:9b6365ddaa8f19dce6eefb',
    messagingSenderId: '826385888674',
    projectId: 'manager-fe707',
    authDomain: 'manager-fe707.firebaseapp.com',
    databaseURL: 'https://manager-fe707.firebaseio.com',
    storageBucket: 'manager-fe707.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGvvJBFUFrXm82lmKLz_2b1FxskpZHU-I',
    appId: '1:826385888674:android:f624f712b2d600c4e6eefb',
    messagingSenderId: '826385888674',
    projectId: 'manager-fe707',
    databaseURL: 'https://manager-fe707.firebaseio.com',
    storageBucket: 'manager-fe707.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP4OmkbQjJ1pdaSvC2oR98hNv8i_2zB7U',
    appId: '1:826385888674:ios:a74bb3f7d901515de6eefb',
    messagingSenderId: '826385888674',
    projectId: 'manager-fe707',
    databaseURL: 'https://manager-fe707.firebaseio.com',
    storageBucket: 'manager-fe707.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseGstatic',
  );

}